// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://encqqawsxugqlcvktolv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuY3FxYXdzeHVncWxjdmt0b2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODM5NTcsImV4cCI6MjA2MzI1OTk1N30.PlRncoL0RPEaQdTmTxU68fZyC-DphRQZ3WmmumTiMRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);